### ISSUE TITLE
Writing virtual references into Icechunk from VirtualiZarr

### ISSUE THREAD

**Issue by TomNicholas** [earth-mover/icechunk#103]
I would like to be able to write virtual references contained in `virtualizarr.ManifestArray` objects to an Icechunk store. 

The user API would be something like 

```python
import virtualizarr as vz

vds = open_virtual_dataset('file.nc')

vds.virtualize.to_icechunk(icechunkstore)
icechunkstore.commit('<todays-date>')
```

but this requires me to write a virtualizarr writer, following the same general idea of the [prototype zarr chunk manifest writer](https://github.com/zarr-developers/VirtualiZarr/blob/47a5e8702e44f71bb355bcba0ff6214fe6d09d83/virtualizarr/writers/zarr.py#L11). So I guess I want an API something like:

```python
icechunkstore[<array-name>] = manifestarray
```

In general I will want to write an entire virtual dataset (or even virtual datatree) in at once, so that that can be committed as a new snapshot. That means writing virtual references for many arrays, for many groups, and group-level attributes, all in that one virtualizarr method call.

(I know the rust implementation for this is being worked on actively in #85, but this can be closed once there is corresponding python API available that I can use in virtualizarr.)

**Comment by mpiannucci** [comment]
See https://github.com/zarr-developers/VirtualiZarr/pull/256

**Comment by TomNicholas** [comment]
Closed by https://github.com/zarr-developers/VirtualiZarr/pull/256 being merged and released!

I'll open a new issue if any bugs / performance problems are found.
