### ISSUE TITLE
Don't allow to write chunks to invalid chunk coordinates

### ISSUE THREAD

**Issue by paraseba** [earth-mover/icechunk#175]

**Comment by emacollins** [comment]
@paraseba Would like to try and give this one a shot! Let me know any context and background.

**Comment by paraseba** [comment]
@emacollins Great!

So, the key to this one is in the `set_chunk_ref` method of the `Repository` impl. In there we get the Array and apply the requested change. After getting the array, but before applying the change we would need to check if the passed `coord: ChunkIndices` are valid for the array. If they are not, we should fail.

To know if the coordinates are valid, we need to look into the array metadata, which you can find in the response of `Repository.get_array`.

You'll probably need to add a new error case to `RepositoryError`.

Probably some of our tests fail after this change, and also, we'll want to add tests that verify the new behavior.

Let me know if that's enough to get you started or if you want more context. And ping me with any questions.

Thank you!

**Comment by emacollins** [comment]
@paraseba Thanks for the detailed explanation! I think this is enough to get started. I'll familiarize myself about with each of these parts and see what I can do

**Comment by paraseba** [comment]
Sounds great @emacollins ! Take you time and let me know if you have questions.

**Comment by paraseba** [comment]
Another change we would need, but it could be done in a separate ticket, would be to make sure that if the user shrinks an array by changing its metadata, all the chunks that are outside of the array bounds disappear from the manifest.

**Comment by paraseba** [comment]
Great work @emacollins . My notes:

> Alright, it doesn't look like I am able to publish my branch for this (permissions error?)

You need to fork the repository, push a new branch there, and then create a pull request once it's ready. I can also review the fork branch before you want to create a PR.

> add a method to ZarrArrayMetadata that checks if a given set of coordinates is valid for the array.

Great

> Let me know if this makes sense

Yes, very much so. That sound like a fine approach.

A few more notes:

* I'd probably name the method something like `valid_chunk_coordinates`
* Rust has a mechanism for documentation strings, google around and you'll find a whole syntax using stuff like ///
* You could use `debug_assert_eq` instead. Maybe we should add this validation when metadata is written and updated too, to make sure we fail early.
* With a quick look your code seems to do the right thing, it's just not idiomatic (as expected as you learn the language). In Rust we usually try to avoid mutable variables, unless they are really necessary. We also try to avoid explicit index based looping. Take a look at the [`Iterator`](https://doc.rust-lang.org/std/iter/trait.Iterator.html) trait, it has a bunch of very useful methods that get used all the time for this kind of thing.
* Here are some more tips:
  * You could write a helper function that returns an iterator to the maximum chunk index permitted (or even a `Vec` would work, but an Iterator may be better practice)
  * Then you can `zip` the results of that function with the request.
  * Then you verify that `all` elements in the zip result are valid.
  * Relevant functions: [`zip`](https://doc.rust-lang.org/std/iter/fn.zip.html), [`all`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.all)

**Comment by emacollins** [comment]
@paraseba Great, thank you very much for all the detail! I really wanted to make sure I got the core logic of what was needed down first. Now time to clean up and make sure this is implemented idiomatically :)

**Comment by emacollins** [comment]
Created a [draft pr](https://github.com/earth-mover/icechunk/pull/395) with my progress. Please tear it apart (when you have the time, no rush!) to help me learn. @paraseba
