### ISSUE TITLE
store.checkout should raise an error if snapshot_id does not exist

### ISSUE THREAD

**Issue by jhamman** [earth-mover/icechunk#235]
Icechunk let's you checkout a reference, even if it doesn't exist:

```python
store.checkout(snapshot_id="FOOOBARSPAM123456789")
```

If the snapshot does not exist, it would be much nicer to raise an error earlier.

**Comment by dcherian** [comment]
How do we know if a snapshot ID is valid? IIUC we'd have to list `prefix/s` to figure that out?

**Comment by paraseba** [comment]
`storage.fetch_snapshot` ?
