### ISSUE TITLE
[Docs] errors in xarray page

### ISSUE THREAD

**Issue by callumrollo** [earth-mover/icechunk#280]
When working through the [xarray page of the docs](https://icechunk.io/icechunk-python/xarray), I encountered a few errors/omissions that added friction to my quick attempt at using icechunk + xarray:

- [x] import line imports modules `IcechunkStore`, `StorageConfig` from `icechunk`; later `icechunk.StorageConfig` is called, which fails as `icechunk` itself was not imported.
- [x] `ds = xr.tutorial.open_dataset('rasm')` requires the packages `pooch` and `netCDF4` to be installed, this should be included in the instructions
- [x] Final line states that `Notice that this second xarray.Dataset has a time dimension of length 18 whereas the first has a time dimension of length 36`, but the first has dimenstions `(y: 205, x: 275, time: 18)`. I think this is just a copy-paste error when making the docs

I will submit 3 PRs to remedy these. Looking forward to working with this package!

**Comment by paraseba** [comment]
Closed by @callumrollo PRs. Thank you.
