### ISSUE TITLE
Removed "await" from era5 notebook to get it running

### ISSUE THREAD

**Issue by rsignell** [earth-mover/icechunk#296]
When I tried first running [the era5 notebook linked in the blog post,](https://github.com/earth-mover/icechunk/blob/main/icechunk-python/notebooks/performance/era5_xarray-Icechunk.ipynb) I was getting errors like:
```
TypeError: object IcechunkStore can't be used in 'await' expression
```
I didn't really know what I was doing, but when I removed the `await` references, [I got the notebook to run](https://gist.github.com/rsignell/fc86ccaa1c9bf25a0d83c2e728d1a529) (using a Coiled Jupyterlab instance on AWS) and the performance seemed similar to Ryan's original results?

**Comment by jhamman** [comment]
Thanks @rsignell - we can take another pass through these notebooks and clean this up. We just changed the store this week to use asynchronous API for the create/open/commit methods.

**Comment by rsignell** [comment]
No, icechunk is the great stuff!! 😜
