### ISSUE TITLE
pickling of icechunk stores is broken

### ISSUE THREAD

**Issue by dcherian** [earth-mover/icechunk#348]
```python
import icechunk
import pickle
store = icechunk.IcechunkStore.create(
    storage=icechunk.StorageConfig.memory("")
)
pickle.loads(pickle.dumps(store))
```

**Comment by mpiannucci** [comment]
I don't think you can pickle a memory store. If you notice, the pickle test works, but the zarr store one doesn't because it uses a memory store. If you change the zarr store test to use a filestore it will work. 

This makes sense, at least for now that they will not load the same memory.
