### ISSUE TITLE
documentation site is broken

### ISSUE THREAD

**Issue by thopri** [earth-mover/icechunk#359]
I get the following error when trying to connect to icechunk.io

```
Secure Connection Failed

An error occurred during a connection to icechunk.io. PR_END_OF_FILE_ERROR

Error code: PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.

```

**Comment by rabernat** [comment]
We are not able to reproduce this problem. Site looks fine to me. Where are you connecting from?

**Comment by thopri** [comment]
Ah, have just refreshed the cache and I now get an http only error (firefox is set to warn for http connections). Bypassing that shows that the URL has been blocked by my institution. Annoying! Its due to the fact the domain is recently registered so it should resolve it self and there is nothing you guy can do. Thanks for the quick response!

**Comment by paraseba** [comment]
Thank you @thopri
