### ISSUE TITLE
Store shouldn't be read_only after checking out a branch

### ISSUE THREAD

**Issue by mpiannucci** [earth-mover/icechunk#439]
Checking out a tag or snapshot should still set the store to read_only

**Comment by dcherian** [comment]
Don't we want to preserve read-only status on checking out a branch?

**Comment by dcherian** [comment]
One complication is
```python
store = IcechunkStore.open_existing(..., read_only=False)
store.checkout(snapshot=...) # now read-only
store.checkout(branch=...) # preserves read-only
```

Which I think is OK. People should be comfortable explicity marking stores as writeable.

I can may be see auto-setting writeable on `new_branch` because what else would you do with a new branch?
