### ISSUE TITLE
Are chunk keys content-addressed like indicated in ArrayLake?

### ISSUE THREAD

**Issue by y4n9squared** [earth-mover/icechunk#460]
The ArrayLake [documentation](https://docs.earthmover.io/concepts/version-control-system#content-addressable-chunk-storage) states that Zarr chunk keys are generated via the hash of its data.

> When writing new chunk data, Arraylake uses a "content addressable" strategy to pick the keys to use in the object store; it computes a hash for each piece of data and then uses that hash as the key.

One artifact of this choice that I have noticed is that, when using Zarr's default compressor (i.e. Blosc w/ LZ4) on multiple threads, the chunk output is not deterministic and therefore the hash changes even though the data is logically identical, which I suppose causes you to write out multiple copies of the same chunk?

You can get deterministic hashes back by setting `numcodecs.blosc.num_threads(1)` but then performance of the shuffle filter tanks.

Is Icechunk employing the same content-addressable strategy?

**Comment by rabernat** [comment]
No. We dropped that when moving from Arraylake repos to icechunk. 

Icechunk keys are a form of random UID.

**Comment by dcherian** [comment]
We should document this in the spec: https://icechunk.io/spec/

**Comment by y4n9squared** [comment]
> Icechunk keys are a form of random UID.

Interesting. So while there is still no locking necessary, it will be the case that an array with say large swaths of identical data chunks (e.g. all 1s) will now occupy multiple redundant blobs. Out of curiosity, what was the motivation for moving away from content-addressable keys?

**Comment by paraseba** [comment]
> what was the motivation for moving away from content-addressable keys

In order of increasing relevance:

* There is a (small) performance impact of computing the hashes.
* Arraylake had this feature but we didn't see important storage savings. Repeated chunks are usually very compressible.
* Content addressable stores make it much harder to implement certain features, such as garbage collection.

**Comment by y4n9squared** [comment]
Thanks for confirming both the initial question and the follow-ups.
