### ISSUE TITLE
`Repository.tag` is confusing

### ISSUE THREAD

**Issue by dcherian** [earth-mover/icechunk#492]
It returns the `SnapshotId` associated with  a tag name.

Perhaps we should call it `lookup_tag` and rename `.branch_tip` to `lookup_branch`?

**Comment by mpiannucci** [comment]
I like that change. I chose the name tag and knew it was bad

**Comment by jhamman** [comment]
The GitPython project has a pretty intuitive API. https://gitpython.readthedocs.io/en/stable/tutorial.html#examining-references

```python
repo.create_tag(ref: str)
repo.delete_tag(ref: str)
repo.tags -> Iterable[TagReference]
```
