### ISSUE TITLE
Error creating local filesystem repositories using relative paths

### ISSUE THREAD

**Issue by maxrjones** [earth-mover/icechunk#500]
In case you can't hear it enough, thank you for creating this awesome open-source library!

I was motivated to work based on the main branch (currently on commit [e3a710b31ce1d6d8a06d2a487c3f8ee7166c42d2](https://github.com/earth-mover/icechunk/commit/e3a710b31ce1d6d8a06d2a487c3f8ee7166c42d2)) because it aligned with the published docs. However, I receive an unintuitive error when using a relative path for a local storage repository. In the code below, I first verify that `icechunk.Repository.create` works with absolute paths. I then try to create repositories using two forms of relative paths. The relative folders are created by `StorageConfig.filesystem`, but the error `Unable to canonicalize filesystem root` is given on `Repsoitory.create`. If this is part of the refactoring churn and it would be a more appropriate solution to deploy versioned docs, I would be glad to help set that up in the CI.

```Python
from icechunk import Repository, StorageConfig
import tempfile

# Success
tmpdir = tempfile.mkdtemp()
repo = Repository.exists(StorageConfig.filesystem(tmpdir))

# Success
repo = Repository.create(StorageConfig.filesystem('/Users/max/Documents/Code/developmentseed/virtualize/.vscode/icechunk-repos/test'))

# Failure
config = StorageConfig.filesystem("./.vscode/icechunk-repos/test-1")
repo = Repository.create(config)

# Failure
config = StorageConfig.filesystem(".vscode/icechunk-repos/test-2")
repo = Repository.create(config)
```

Expected output: a new repository
Truncated error:
```
icechunk.IcechunkError: storage error: error contacting object store Generic LocalFileSystem error: Unable to canonicalize filesystem root: /.vscode/icechunk-repos/test-1
```

**Comment by maxrjones** [comment]
After circumventing this issue by using an absolute path, I ran into the NotImplementedError for setting virtual references. So just a note in case anyone else stumbles upon this issue that I think the more appropriate path is to continue to use `icechunk=0.1.0a7` and look at https://github.com/earth-mover/icechunk/tree/a8c33b81d329c32a8e34e7151a1a71620967067a/docs/docs/icechunk-python for the docs associated with that tag, rather that using the published docs and the main branch.

**Comment by mpiannucci** [comment]
Thanks for reporting @maxrjones . We are working on adding back the virtual references now (see the PRs). Your first ticket is indeed a bug so we'll check that out. 

As far as versioned docs go, it's something we need for sure

**Comment by mpiannucci** [comment]
I think this should be fixed now! Let me know if you hit issues with it!
