### ISSUE TITLE
Trouble with pip install

### ISSUE THREAD

**Issue by kingkong-cmd** [earth-mover/icechunk#514]
Hi guys,

Wanted to try this out, but failed before I got started. Is this on my side, or something wrong with package?

```
> pip install icechunk
ERROR: Could not find a version that satisfies the requirement icechunk (from versions: none)
ERROR: No matching distribution found for icechunk
```

**Comment by rabernat** [comment]
Could you share more details about your environment? (Operating system, Python version)

Plus the full pip error message?

**Comment by kingkong-cmd** [comment]
> Could you share more details about your environment? (Operating system, Python version)
> 
> Plus the full pip error message?

Apologies. I didn't run with verbose flag. That gave a pretty clear answer.

```
> pip install -v icechunk
Link requires a different Python (3.10.12 not in: '>=3.11'): https://files.pythonhosted.org/packages/f8/74/4aceb77404de86960a56c40ade6e85bd186a184f4895f1864a8bb2ffb90f/icechunk-0.1.0a1.tar.gz#sha256=fc61f8e3df2ca1e5936a3d4e61dd3eb6cc7714548238366b4b2f39a6cc3ab68d (from https://pypi.org/simple/icechunk/) (requires-python:>=3.11)
```

**Comment by rabernat** [comment]
Glad you got it solved! We're looking forward to your feedback on Icechunk!

**Comment by kingkong-cmd** [comment]
Thanks. Any chance you could open up the discussion tab here on github? Makes it easier to ask questions on how to use etc.

**Comment by rabernat** [comment]
> Any chance you could open up the discussion tab here on github?

Thanks for this suggestion. We will investigate it and decide whether to add discussions. In the meantime, feel free to ask usage questions via issues.
